name: Deploy to GitHub Pages
on:
push:
branches: [ main ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: subosito/flutter-action@v1
with:
channel: "stable"
- run: flutter config --enable-web
- name: Dependencies
working-directory: web-app
run: flutter pub get
- uses: bluefireteam/flutter-gh-pages@v7
with:
workingDir: web-app
baseHref: /